#!/bin/bash
# script from https://git-annex.branchable.com/install/Docker/
CONT_NAME=${CONT_NAME:-git-annex:latest}
# if in git repo, mount root as /data, and cd into relative subdir
# if not, mount cwd as /data
data_dir=$HOME/Git-Annex/
# if run by git, assume command is git-annex
# otherwise, don't assume, to allow other uses
cmd=git-annex
exec docker run --mount type=tmpfs,destination=/tmp/ -it --rm \
    -u $(id -u):$(id -g) \
    -v /etc/passwd:/etc/passwd:ro \
    -v $HOME/.ssh:$HOME/.ssh \
    -v $HOME/.gnupg:$HOME/.gnupg \
    -v $HOME/.gitconfig:$HOME/.gitconfig \
    -v "$data_dir":/data \
    ${AWS_ACCESS_KEY_ID:+-e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"} \
    ${AWS_SECRET_ACCESS_KEY:+-e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"} \
    ${B2_ACCOUNT_ID:+-e B2_ACCOUNT_ID="$B2_ACCOUNT_ID"} \
    ${B2_APP_KEY:+-e B2_APP_KEY="$B2_APP_KEY"} \
    -w "/data" \
    $CONT_NAME $cmd "$@"
